# Site Settings
locale                   : "en-US"
title                    : "hacefresko"
title_separator          : "~"
url                      : https://www.hacefresko.com
repository               : "hacefresko/hacefresko.github.io"

# SEO
google_site_verification: "zDnKQCYsgAZXSg-xueOayFFrYOicAVaWxGfP1E93LJk"