# Site Settings
title                    : "hacefresko"
url                      : https://www.hacefresko.com
repository               : "hacefresko/hacefresko.github.io"

# SEO
google_site_verification: "zDnKQCYsgAZXSg-xueOayFFrYOicAVaWxGfP1E93LJk"

plugins:
  # RSS Feed
  - jekyll-feed
  - jekyll-redirect-from